name: sliver_list_watcher
version: 1.0.4
description: A custom widget for observing scroll events in a sliver list.
homepage: https://github.com/Hama835/sliver_list_watcher
repository: https://github.com/Hama835/sliver_list_watcher.git

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

